{
 "title": "CISCO NEXUS SERIES 3000 TESTES",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "TRANSCIEVERS GBIC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CORRENTE",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:859",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "SWBSA711N01 Teste: Transciever",
        "."
       ],
       "text": "replaceAlias(SWBSA711N01 Teste: Transciever, .)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": { "filter": "/Corrente/" },
     "itemTag": { "filter": "/Corrente/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TENSÃO",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1509",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "SWBSA711N01 Teste: Transciever",
        "."
       ],
       "text": "replaceAlias(SWBSA711N01 Teste: Transciever, .)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": { "filter": "/Voltagem/" },
     "itemTag": { "filter": "/Voltagem/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "TEMPERATURA 🔥",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:913",
       "def": {
        "category": "Alias",
        "defaultParams": [
         "/(.*)/",
         "$1"
        ],
        "name": "replaceAlias",
        "params": [
         { "name": "regexp", "type": "string" },
         { "name": "newAlias", "type": "string" }
        ]
       },
       "params": [
        "SWBSA711N01 Teste: Transciever",
        "."
       ],
       "text": "replaceAlias(SWBSA711N01 Teste: Transciever, .)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": { "filter": "/Temperatura/" },
     "itemTag": { "filter": "/Temperatura/" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SINAL RX",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1095",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/1 RX" ],
       "text": "setAlias(Ethernet1/1 RX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/1(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 25827" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1116",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/3 RX" ],
       "text": "setAlias(Ethernet1/3 RX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/3(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 25859" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1137",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/4 RX" ],
       "text": "setAlias(Ethernet1/4 RX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/4(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 25875" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1158",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/48 RX" ],
       "text": "setAlias(Ethernet1/48 RX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/48(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 26579" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1185",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/8 RX" ],
       "text": "setAlias(Ethernet1/8 RX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/8(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 25939" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1212",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/19 RX" ],
       "text": "setAlias(Ethernet1/19 RX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/19(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 26115" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1239",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/28 RX" ],
       "text": "setAlias(Ethernet1/28 RX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/28(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 26259" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1266",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/29 RX" ],
       "text": "setAlias(Ethernet1/29 RX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/29(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 26275" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SINAL TX",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1335",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/1 TX" ],
       "text": "setAlias(Ethernet1/1 TX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/1(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 25828" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1356",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/3 TX" ],
       "text": "setAlias(Ethernet1/3 TX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/3(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 25860" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1377",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/4 TX" ],
       "text": "setAlias(Ethernet1/4 TX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/4(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 25876" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1398",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/48 TX" ],
       "text": "setAlias(Ethernet1/48 TX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/48(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 26580" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1419",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/8 TX" ],
       "text": "setAlias(Ethernet1/8 TX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/8(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 25940" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1440",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/19 TX" ],
       "text": "setAlias(Ethernet1/19 TX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/19(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 26116" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1461",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/28 TX" ],
       "text": "setAlias(Ethernet1/28 TX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/28(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 26260" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1482",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Ethernet1/29 TX" ],
       "text": "setAlias(Ethernet1/29 TX)"
      }
     ],
     "group": { "filter": "TESTE" },
     "host": { "filter": "SWBSA711N01 Teste" },
     "item": {
      "filter": "Transciever (Ethernet1/29(dBm)) Sinal"
     },
     "itemTag": { "filter": "Transciever: 26276" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}